theme: jekyll-theme-slate
title: iSonork's Projects
logo: Potato Piece.png
description: Potato Piece https # Displays as site description meta tag for site
copyright: 2021 iSonork, Inc. # appears in footer
breadcrumb_home_name: Home # display name for "Home" path in the breadcrumb
tableofcontents: Table of Contents # text that appears before in-page table of contents
expandall: Expand All # appears as text in sidebar to expand all levels
collapseall: Collapse All # appears as text in sidebar to collapse all levels
search_placeholder_text: Search ... # appears as placeholder in search field
no_search_results_found: No matches found. Try using other keywords?
feedback_link_name: Feedback # name of Feedback link
feedback_subject_line: Feedback about docs # Auto-filled Subject link of email
github_edit_button_text: Edit on GitHub # text for github button
